### ISSUE TITLE
Applescript "thumbs up" shouldn't be a toggle

### ISSUE THREAD

**Issue by aclark73** [HermesApp/Hermes#196]
The suggestion on issues like #159 is that the user map keys to Applescript, eg.

```
tell application "Hermes" to thumbs up
```

The only problem with this particular command is that it operates just like pressing the menu bar button, which is actually a toggle.  The toggle works on the menu bar because the user can see the current state, but an Applescript is much more likely to be run blindly; the result is that this often results in the current song being de-liked instead.

This is pretty easily fixable in Applescript like

```
tell application "Hermes"
    if the current song's rating is not 1 then thumbs up
end tell
```

but it's not obvious from the outset that this is necessary, and it seems like this check should really be in the application's Applescript handler anyway.

**Comment by devangnegandhi** [comment]
@corypina Your solution works like a charm. Maybe documenting this will help

**Comment by nriley** [comment]
Agreed — don't think that changing the semantics of the existing scripting command is a good idea, but both the rating and the “thumbs up” command are better documented now.
