### ISSUE TITLE
Audio quality degredation

### ISSUE THREAD

**Issue by pstew** [HermesApp/Hermes#205]
Hello,

I notice a reduction in the quality/bitrate of songs over time. One song will be playing with relatively high quality, but then the next song will be potato quality (the voice track is as loud as/louder than the music and the music is muffled). It definitely sounds like the bitrate is dropping. Does Hermes auto-correct the quality of the audio based on internet connection or connectivity? I understand that Pandora streaming bitrate isn't the highest quality, but a song will play early in the day sounding one way and then replay hours later sounding like a very low bit rate. I'm using a new (2014) 15" MBP. Thanks!

**Comment by nriley** [comment]
Is this still happening? I have better debug messages in 1.2.8 and later which should help to troubleshoot this further, if it is still a problem.

**Comment by Skinner927** [comment]
I haven't noticed any issues.
