### ISSUE TITLE
feature request: show "now playing" info in menubar

### ISSUE THREAD

**Issue by johnny-love** [HermesApp/Hermes#208]
similar to what [QuickTunes](http://www.dbachrach.com/opensoft/index.php?page=QuickTunes) does for iTunes, configurable "now playing" info directly in the menubar would be great. "song / artist" would be my preference. maybe use pianobar's format_nowplaying_song?

**Comment by giantspeck** [comment]
I currently just use GeekTool to do this.  I have mine set to show the artist and title of the currently playing song and then I have it set to "Keep on top".

**Comment by smartwatermelon** [comment]
@giantspeck Would you mind sharing your GeekTool geeklet for this purpose?

**Comment by giantspeck** [comment]
@smartwatermelon I apologize for the late response, but I've uploaded the two geeklets [here](https://drive.google.com/file/d/0B2ZmzFd0HISFaEtJMTdfOVNSWkk/view?usp=sharing).  You need to install the Album Art geeklet first to get the Now Playing geeklet to work properly.  I've also included a screenshot of the geeklet in action.

![geeklet](https://cloud.githubusercontent.com/assets/8790458/6428692/dc72126e-bf4e-11e4-936c-2e7007412b1f.png)

**Comment by smartwatermelon** [comment]
@giantspeck no apology necessary and thank you.

**Comment by fritz-fritz** [comment]
I have my GeekTool configured like this (Yes that's a progress bar on the bottom):
![screen shot 2015-04-25 at 11 27 56 am](https://cloud.githubusercontent.com/assets/5253894/7333450/290af652-eb3e-11e4-8a85-b96fd3492bb4.png)

![screen shot 2015-04-25 at 11 29 12 am](https://cloud.githubusercontent.com/assets/5253894/7333459/568ce1ee-eb3e-11e4-9aa6-8557a05d1d78.png)

This is actually several geeklets and a script. It works with both Hermes and iTunes. If anyone is interested I can post them up.

**Comment by lbreaux** [comment]
@fritz-fritz I'd greatly appreciate those geeklets for Hermes. :D

**Comment by nriley** [comment]
OK, thanks to @paullj1 we've got this implemented.  Please try out 1.2.9b1:

https://github.com/HermesApp/Hermes/releases/tag/v1.2.9b1

**Comment by nriley** [comment]
This is now released as 1.3.0.
