### ISSUE TITLE
After upgrade to 1.2.5, media buttons on keyboard now only work when Hermes has focus

### ISSUE THREAD

**Issue by kellybyrd** [HermesApp/Hermes#211]
I've been using the "Control Playback with Media Keys" feature for several releases. I just upgraded to 1.2.5 and found that this is now broken for me (OSX 10.10.1) if Hermes is not the foreground app.

Please fix ASAP!

**Comment by nriley** [comment]
We didn't change anything in 1.2.5, sorry.  Media keys work fine for me in the background on 10.10.1.

**Comment by kellybyrd** [comment]
Huh. After the forth restart, this works for me to now.
