### ISSUE TITLE
why won't Hermes offer a feature to keep computer awake...

### ISSUE THREAD

**Issue by carart** [HermesApp/Hermes#219]
does Hermes offer a feature to keep computer awake? Strangely to me, they make it sound like a good thing that it let's the computer sleep. I have to keep going over every 15 minutes to restart music. Why?

**Comment by winny-** [comment]
Not currently. Personally, I use hot corners to keep my computer awake.

**Comment by carart** [comment]
thanks but my point is, why would I want to have to either set my computer never to sleep, have to keep moving the cursor very 14' 59" to keep it awake just so I can use Hermes? Pandora keeps my computer awake while with Hermes, I have to continually go over to my computer to keep it awake or wake it and restart Hermes. So inconvenient I'm rather surprised anyone would bother with this app unless the only way you listen to music is while you're actually working on your computer. My computer is my stereo system thru out my home. But thanks for the reply.
