### ISSUE TITLE
Pandora - Like/Dislike Disabled

### ISSUE THREAD

**Issue by muir71** [HermesApp/Hermes#221]
I don't have the option to like or dislike a song now in Hermes. I've attached the screenshot so you can see exactly what I'm seeing. Let me know if any other info is needed.
![screen shot 2015-04-08 at 11 47 18 am](https://cloud.githubusercontent.com/assets/11858155/7051367/23bbe460-dde5-11e4-98b8-4ba50ad9cfce.png)
![screen shot 2015-04-08 at 11 45 32 am](https://cloud.githubusercontent.com/assets/11858155/7051370/265c49b2-dde5-11e4-8da3-2a2d95189a84.png)
![screen shot 2015-04-08 at 11 47 43 am](https://cloud.githubusercontent.com/assets/11858155/7051373/2855a06a-dde5-11e4-9374-2b2fbc0307cd.png)

**Comment by nriley** [comment]
Does this happen with every station? I can't reproduce it unfortunately.

**Comment by muir71** [comment]
Wow, I feel somewhat foolish now. I changed the station in Hermes and all other stations work fine as they should except for this one. So I went directly into Pandora's website, found out that it's a shared station, and not my own. Sorry for the confusion, you can go ahead and resolve this issue :)

**Comment by nriley** [comment]
Thanks. Not entirely your fault — we should probably give more of a hint in the UI *why* you can't do it.
