### ISSUE TITLE
Airplay / Output Device Selection

### ISSUE THREAD

**Issue by bradmkjr** [HermesApp/Hermes#222]
Just curious if it will be possible to allow Hermes to let the user select which audio device the app uses?
I use airplay for music, but don't want to switch all my output to airplay, as then all notifications will play over the airplay instead of just the internal speaker.

Sample code:
https://developer.apple.com/library/mac/samplecode/CAPlayThrough/Introduction/Intro.html#//apple_ref/doc/uid/DTS10004443

If this is something that seems possible, I'm willing to take a stab at it, but I wanted to open it to discussion prior to starting in case there was a technical reason why it wouldn't work.

Thanks
Brad

**Comment by nriley** [comment]
This was possible but has been essentially broken in 10.11 as AirPlay audio devices are no longer exposed as they once were.  Sorry :-(
