### ISSUE TITLE
Last.fm app url

### ISSUE THREAD

**Issue by rlex** [HermesApp/Hermes#225]
...still points to old hermes page. JFYI.

And thanks for your app.

**Comment by winny-** [comment]
Thank you for pointing this out.

**Comment by winny-** [comment]
Could you give me a URL to the page where you found an old link?

**Comment by rlex** [comment]
It's "now playing with" when you scrobbling something to last fm.

**Comment by winny-** [comment]
Okay I've update the URL (and added an image to the app), so I'll go ahead and close this issue. Please reopen this issue if you find things are not in order.
