### ISSUE TITLE
Port to iOS?

### ISSUE THREAD

**Issue by Aahung** [HermesApp/Hermes#229]
Any plan to make it to iOS?

**Comment by nriley** [comment]
I imagine there may be some issues with App Store approval given reverse engineering of Pandora's API. Also, that would require several orders of magnitude more developer time than currently appear available. Finally, the Pandora iOS client is nowhere near as bad as the Web site.

But hey, if you're volunteering, the code is all there...

**Comment by giantspeck** [comment]
I think the only way this would be feasible is if it were developed for jailbroken iPhones.

If your iOS device is jailbroken and you would like to see this ported, you may try requesting it on Reddit:  /r/jailbreak, /r/tweakbounty, or /r/requestedtweaks

**Comment by Aahung** [comment]
I see, but it is not ideal.
I cannot find any other 3rd party apps online, maybe there is some invisible rules prevents such apps online. :-(

**Comment by winny-** [comment]
I think this following part of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) excludes third-party Pandora clients:
  * § 8.1: Apps may not use protected third party material such as trademarks, copyrights, patents or violate 3rd party terms of use. Authorization to use such material must be provided upon request.

And if we look at the [Pandora ToS](https://www.pandora.com/legal) you'll find it explicitly forbids:
  * § 9 (iv) translate, reverse engineer, decompile, disassemble, modify or create derivative works based on the Pandora Service, a Pandora application or any portion thereof except as expressly allowed under applicable law;
  * § 9 (v)	circumvent any technology used by Pandora or its licensors to protect content accessible via the Pandora Service;

So I don't think Apple would like this at all.

**Comment by alaska** [comment]
As others have stated, this would almost certainly violate both Apple's TOS *and* Pandora's.  Not only that, but it would probably introduce a higher degree of issue/bug churn. Unless someone is willing to sally forth and develop this port entirely on their own with the knowledge that it will never run on anything other than jailbroken phones, I think this issue should probably be closed.

**Comment by nriley** [comment]
Sounds good to me.  In any case, nobody seems interested in helping out on the Mac version, which is at least relatively functional at the moment (#237).
