### ISSUE TITLE
Segmentation fault on launch

### ISSUE THREAD

**Issue by psihonavt** [HermesApp/Hermes#231]
Trying to launch Hermes on OS X Yosemite:
```bash
➜  nimble-server git:(develop) ✗ /Applications/Hermes.app/Contents/MacOS/Hermes
[1]    11875 segmentation fault  /Applications/Hermes.app/Contents/MacOS/Hermes 
```
Have to say that just few days ago it was working okay. Should I cleanup some settings/cache stuff? Or maybe there is a way to launch hermes with some debug output?

**Comment by winny-** [comment]
There should be a CrashReport

**Comment by winny-** [comment]
You can view the DiagnosticReport in Console.app -> ~/Library/Logs -> DiagnosticReports -> Select the Hermes log that corresponds to when the segfault happened.

You can try launching Hermes with logging (hold down option during launch), but I think the above item should disclose enough information.

If I were to take a guess, this is probably related to a corrupted state file, but we'll know for certain after you post the above DiagnosticReport.

**Comment by psihonavt** [comment]
Thanks for detailed instructions. Here is the report https://gist.github.com/psihonavt/48262e283c0f64b247ba

**Comment by winny-** [comment]
Can you share you settings:

`defaults read com.alexcrichton.Hermes`

**Comment by nriley** [comment]
@psihonavt - do you have a proxy server configured in System Preferences?  If so, could you provide the output of `scutil --proxy`? Thanks.

**Comment by psihonavt** [comment]
@winny- 
```bash
defaults read com.alexcrichton.Hermes
{
    "NSToolbar Configuration 523691DA-3184-4F47-A885-9465F8ED1820" =     {
        "TB Display Mode" = 2;
        "TB Icon Size Mode" = 2;
        "TB Is Shown" = 1;
        "TB Size Mode" = 1;
    };
    "NSWindow Frame Hermes Preferences" = "317 404 362 473 0 0 1440 877 ";
    "NSWindow Frame Preferences" = "455 143 240 328 0 0 1440 877 ";
    "NSWindow Frame SUUpdateAlertFrame" = "434 363 575 392 0 0 1440 877 ";
    SULastCheckTime = "2015-05-17 15:07:17 +0000";
    audioQuality = 0;
    enabledProxy = 2;
    "hermes.last-station" = 1088976142556912774;
    "hermes.volume" = 100;
    lastPrefPane = network;
    openDrawer = 0;
    "pandora.username" = "psihonavt@gmail.com";
    pauseOnScreensaverStart = 0;
    playOnScreensaverStop = 0;
    pleaseBindMedia = 1;
    pleaseScrobble = 1;
    pleaseScrobbleLikes = 0;
    statusBarIcon = 1;
    statusBarIconBlackWhite = 1;
}
```
@nriley 
```bash
scutil --proxy
<dictionary> {
  ExceptionsList : <array> {
    0 : *.local
    1 : 169.254/16
  }
  FTPPassive : 1
  SOCKSEnable : 0
}
```

**Comment by psihonavt** [comment]
following this FAQ https://github.com/HermesApp/Hermes/blob/master/Documentation/FAQ.md#help-hermes-crashes-on-startup-or-behaves-badly helps me.

**Comment by winny-** [comment]
That's very odd that resetting everything resolved the issue. Thank you for sharing your settings. I'll see if I can reproduce this issue.
