### ISSUE TITLE
Download Link on Official Site is down.

### ISSUE THREAD

**Issue by rezon8** [HermesApp/Hermes#233]
Only contact link on official site appears to be this GitHub account, so I am reporting it here.
The download link for the compiled app on the official site is down.

**Comment by winny-** [comment]
Hi!

Thank you for reporting.

**Comment by winny-** [comment]
Note to self, EC2 IP's are pretty expensive. Download link should be back in within several hours. Sorry for the inconvenience.

**Comment by winny-** [comment]
Download URL is back, sorry about that.

**Comment by rezon8** [comment]
No worries. Thank for fixing it so promptly!
