### ISSUE TITLE
QuickMix deletion shouldn't be allowed

### ISSUE THREAD

**Issue by dcondrey** [HermesApp/Hermes#240]
Attempting to delete 'QuickMix' resulted in this error being displayed and it persists indefinitely until closing out and relaunching application.

![screen shot 2015-07-28 at 4 36 00 pm](https://cloud.githubusercontent.com/assets/2615179/8946674/09ef3dca-3547-11e5-9198-399b6264700d.jpg)

**Comment by nriley** [comment]
Yeah, this shouldn't have been allowed. For anyone who is experiencing this problem, please try out https://sabi.net/temp/Hermes-1.2.7b1.zip and see if it works for you.

**Comment by nriley** [comment]
1.2.7 is now released and this problem appears to be fixed for good, I hope! Thanks everyone.
