### ISSUE TITLE
Sleep setting not being honored

### ISSUE THREAD

**Issue by feus4177** [HermesApp/Hermes#241]
I have both "Pause when screen saver starts" and "Pause when screen locks" unchecked, yet when my laptop goes to sleep, the music stops.

**Comment by dotmacro** [comment]
I changed these preferences without re-starting Hermes (from checked to unchecked), and the new settings (don't pause) were honored. Are you still having trouble? If so, do you have the "wake for network access" option checked on the "energy saver" menu in system prefs?

**Comment by feus4177** [comment]
I've stopped using Hermes in favor of [Stream Keys](http://www.streamkeys.com/) for Chrome. I currently have the "Wake for Wi-Fi network access" checked although at the time it might not have been.

**Comment by nriley** [comment]
I can't reproduce this either, sorry.  Please feel free to reopen if it is a problem.
