### ISSUE TITLE
Last.fm Token expired

### ISSUE THREAD

**Issue by cmurockstar** [HermesApp/Hermes#242]
When i try to connect Hermes to my Last.fm account (fresh install) I see:

Connect application
Token expired. Please return to Hermes and try again.

**Comment by nschimme** [comment]
This bug happens for me as well

**Comment by mizterjones** [comment]
This issue persists.

**Comment by ginader** [comment]
same problem here.

**Comment by devkinetic** [comment]
same issue here today

**Comment by nschimme** [comment]
I updated the source code with a fresh token and it still fails. I think Last.fm is bugged.

**Comment by devkinetic** [comment]
@nschimme same error?

**Comment by fritzboyle** [comment]
+1 on this issue. Ive tried several times and fails as described above on the last.fm site, then until I remove the check mark in the app, I continually get a notification for the app "last.fm error: Invalid authentication token supplied"

**Comment by imtehuber1337** [comment]
Last.fm is a big one for me and that's all that is needed for me to continue to use hermes.

**Comment by nriley** [comment]
Figured this one out — nothing to do with the token. Should be fixed in the next version.

**Comment by nriley** [comment]
For anyone who is experiencing this problem, please try out https://sabi.net/temp/Hermes-1.2.7b1.zip and see if it works for you.

**Comment by iyee** [comment]
@nriley Last.fm was okay for me. after upgrading to 1.2.7b1, it complained that token expired without popping up the authorize window. I'd to delete all data of the app in keychain, restart the app, login in pandora and then finally the auth window appears.

**Comment by nriley** [comment]
Hmm, not good. I think this might be because I changed the token so the session token you had in your keychain no longer corresponded to it. I'll try changing it back to test this case.

**Comment by imtehuber1337** [comment]
Good Job, Dude!

[image: Inline image 1]

Played through a song and it scrobbled.  I'm now a permanent user!!!

**Comment by imtehuber1337** [comment]
[image: Inline image 1]

**Comment by nriley** [comment]
@imtehuber1337 — Thanks! (Also, think GitHub is filtering those images, I don't see anything. You probably need to attach them via the Web site rather than email.)

**Comment by nriley** [comment]
@iyee — it was what I thought; sorry for the oversight. I've fixed your issue and posted a new version which handles Last.fm (https://sabi.net/temp/Hermes-1.2.7b2.zip).

**Comment by ginader** [comment]
I tried both yesterday's beta as well as today's and they both have the
same problem for me:
they crash as soon as I have entered my Pandora Password and hit the "sign
in" button.
I deleted everything named "Hermes" in both Keychain and
Library/Application Support without any change.

It did create a plist in the CrashReport folder. Are you're interested in
that?

thanks for maintaining this great app! Keep up the good work :-)

On Mon, May 9, 2016 at 8:44 AM, Nicholas Riley <notifications@github.com>
wrote:

> @iyee <https://github.com/iyee> — it was what I thought; sorry for the
> oversight. I've fixed your issue and posted a new version which handles
> Last.fm (https://sabi.net/temp/Hermes-1.2.7b2.zip).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HermesApp/Hermes/issues/242#issuecomment-217903064>
>



-- 
Cheers Dirk

**Comment by cmurockstar** [comment]
Same for me - quit after entering pandora info. For context, this is a computer that has never had Hermes on it.

**Comment by nriley** [comment]
@ginader — yes, that would be helpful.  I did test the first-launch process on my own Mac and it worked fine, so there must be something different configuration-wise.  I may need to audit some other folks' changes that I merged in; I think some may have been a bit…aggressive about their memory use.

**Comment by ginader** [comment]
hey @nriley here's the crash report: https://gist.github.com/ginader/45218d98c3337fef7c6fbe7de8609333

**Comment by nriley** [comment]
OK, found the problem — this was a crash that only affected Pandora One members.  Give this a shot: https://sabi.net/temp/Hermes-1.2.7b3.zip

**Comment by ginader** [comment]
Woohoo! It works! Thanks a lot @nriley! Are you accepting tips of any kind? I'd love to send you a little token of my appreciation for your great work :-)

**Comment by nriley** [comment]
1.2.7 is now released and this problem appears to be fixed for good, I hope! Thanks everyone.
