### ISSUE TITLE
menu bar icon [feature request]

### ISSUE THREAD

**Issue by bmehling** [HermesApp/Hermes#243]
Just enjoying some tunes and remain baffled by the Hermes icon (I work in healthcare, so the current icon always has a different context for me).

I was thinking rather than focusing on the "branding" of Hermes... what about showing the current album art? I know it'd be tiny, but it would be neat to show the cover art (w/ the play/pause status overlaid) in the menu bar.

There'd have to be some work done to deal with different color menu bars, etc. Probably not a small amount of work, but figured I'd float the idea...  Love the app, BTW!

**Comment by giantspeck** [comment]
What's funny is that in the context of healthcare, particularly in North America, the caduceus is used *incorrectly*.  The caduceus is the staff that was wielded by the Greek god Hermes, but has no relation to medicine whatsoever.

The confusion comes from the fact that the caduceus closely resembles the Rod of Asclepius, which *does* symbolize medicine, as it was wielded by the Greek god Asclepius, a deity associated with medicine.

Greek mythology aside, I personally think the *dock* app needs to be updated, at least to one that blends in well with Yosemite and El Capitan.

**Comment by bmehling** [comment]
Indeed, you're right. Great distinction. I never looked closely enough to notice this staff was missing the snakes!  (-:

**Comment by nriley** [comment]
Please note that Hermes is essentially an abandoned project — if anyone wants to work on fixing this, great, but neither Alex, Winston nor I are actively working on it nor do any of us have any plans to do so in the near future.

This sounds like a great feature idea, FWIW.

**Comment by bmehling** [comment]
Understood @nriley. Thanks for contributing such a great piece of software to the community!

**Comment by nriley** [comment]
Thanks to @paullj1, we've got a beta version which lets you see album art in your menu bar:

https://github.com/HermesApp/Hermes/releases/tag/v1.2.9b1

**Comment by nriley** [comment]
1.3.0 is now out with this feature. Thanks again to @paullj1!

**Comment by bmehling** [comment]
This is so awesome -- great enhancement. Thanks to @paullj1 and @nriley!!

**Comment by GaitherStephens** [comment]
I'm sorry if this is a dumb question, but is Hermes supposed to be visible in the menu bar?  If so, I don't see it.  I'm on Sierra.  Thanks.
