### ISSUE TITLE
An error has occurred with Pandora.

### ISSUE THREAD

**Issue by brandex07** [HermesApp/Hermes#244]
When opening Hermes, as of recently, I get the following error: 
<img width="251" alt="screen shot 2015-10-11 at 12 40 20 pm" src="https://cloud.githubusercontent.com/assets/7494066/10417773/4cf4311c-7015-11e5-94c4-987b01d023f8.png">

When I try to change stations, the error persists.

**Comment by nriley** [comment]
Please note that Hermes is essentially an abandoned project — if anyone wants to work on fixing this, great, but neither Alex, Winston nor I are actively working on it nor do any of us have any plans to do so in the near future.  (For what it's worth, I do not see this on my 10.11 Mac.)

**Comment by GeorgeGo** [comment]
I'm having the same issue on my 10.11 mac. This only started maybe 3 days ago.

**Comment by smartwatermelon** [comment]
Same here, on 10.11.

**Comment by smartwatermelon** [comment]
Update to above: My guess is that Pandora is expiring a login token (or somesuch). When I launch Hermes, I get the error; I quit Hermes, go to Pandora.com and log in, and then re-launch Hermes and it works.

**Comment by nmelnick** [comment]
Similar to above, if within Hermes I go to the Pandora menu, then to Sign out, and reauthenticate, I'm back in business.

**Comment by ericworking** [comment]
That usually shows up when I launch it using 10.11. Pressing Try Again somewhere between 2-10 times in a row will usually fix it.

**Comment by sephamorr** [comment]
I fixed this issue in this fork: https://github.com/sephamorr/hermes

**Comment by carly427** [comment]
Yeah, I did what @ericworking did and it worked. I got the same message as you did @brandex07 on my MacBook Air 10.11.1 version (El Capitan and it worked.) 
I really like this app tho because it's very useful!

**Comment by scottsievert** [comment]
@sephamorr you should submit a pull request with your fork. I'd love to see that!

**Comment by nriley** [comment]
For anyone who is experiencing this problem, please try out https://sabi.net/temp/Hermes-1.2.7b1.zip and see if it works for you.

**Comment by ryanbmilbourne** [comment]
@nriley I downloaded your beta and got the following dump when starting:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (0), function -[URLConnection start], file /Users/nicholas/Documents/Development/Hermes/Sources/URLConnection.m, line 105.
```

**Comment by nriley** [comment]
That's an assertion that fires when it can't open a connection to the server, but of course I've never seen anything like it. Could you attach the full crash log? Thanks.

**Comment by Skinner927** [comment]
It seems what's happening is the application was configured/compiled with absolute paths on your system nriley and it's failing because it can't fine a specified file.

Here's the crash log:
[hermes_dump.txt](https://github.com/HermesApp/Hermes/files/255348/hermes_dump.txt)

**Comment by nriley** [comment]
Thanks, that is helpful. I can't reproduce it, but I think that assertion may not actually need to be there.

Try this one: https://sabi.net/temp/Hermes-1.2.7b2.1.zip

If it still fails to work, please attach a crash report (if any) and if it fails to work but *doesn't* crash, there should be a line in Console which looks like "Expected read stream to be open, but it was not".  If you can copy and paste that, I'd appreciate it.

**Comment by Skinner927** [comment]
@nriley No crash, but it doesn't work. The loading wheel goes for a little longer than it used to but eventually displays the attached generic error.

I'm not experienced with xcode or objective-c but I would be more than happy to load this project up in xcode and and set some breakpoints and give feedback if that would be helpful. Let me know. 

![hermes-err-screen](https://cloud.githubusercontent.com/assets/1518323/15122984/8a2476ac-15ef-11e6-8a42-f4131e408586.png)

**Comment by nriley** [comment]
Oh well, it was worth a shot.  I still have not been able to replicate this.  I tried simulating a bad network connection from Network Link Conditioner, and anything short of "Very Bad Network" (10% packet loss) works just fine for me.

You can try building Hermes from source (make sure to use the "Hermes" rather than "Hermes (Release —…)" target. Run it until it fails and email me the console log — my username at sabi dot net. Thanks.

**Comment by Skinner927** [comment]
@nriley Curent master has the latest fixes? The modifications you did for the b2.1 build don't seem to have been pushed.

**Comment by nriley** [comment]
Good point, I didn't even commit them. Pushed.

**Comment by nobecutan** [comment]
Had the same `Assertion failed: (0), function -[URLConnection start], file /Users/nicholas/Documents/Development/Hermes/Sources/URLConnection.m, line 105.` issue. Was fixed before I could say so. Great work @nriley. Thanks a lot!

**Comment by Skinner927** [comment]
@nriley was kind enough to respond to my emails and sent me a built version that works! I hope he doesn't mind me posting this up.

https://sabi.net/temp/Hermes-1.2.7b3.zip

**Comment by nriley** [comment]
1.2.7 is now released and this problem appears to be fixed for good, I hope! Thanks everyone.
