### ISSUE TITLE
Playback shortcuts

### ISSUE THREAD

**Issue by hgpt** [HermesApp/Hermes#246]
It would be really nice if you could implement custom keyboard shortcuts like Play/Pause/Skip/Thumbs UP/Down. Other players like Pandorita or PandaBar do have them, but Hermes seems more appealing to me.

**Comment by nriley** [comment]
You can script Hermes play/pause/thumbs up/down, and use a utility like FastScripts or Keyboard Maestro to trigger them.  (I wrote my own — https://github.com/nriley/StreamVision, but probably not for general use).
