### ISSUE TITLE
Media Keys Not Honored

### ISSUE THREAD

**Issue by jaredpetry** [HermesApp/Hermes#250]
In OS 10.11.2, the media keys (play, pause, forward, back keys) are not being honored in Hermes. When pressing these keys, the iTunes app opens instead of controlling Hermes.

**Comment by pstew** [comment]
This is likely a Mac/OSX issue. Try this fix: http://www.thebitguru.com/projects/itunes-patch

**Comment by jaredpetry** [comment]
Thanks for your reply! Better late than never. :) The issue was resolved after a subsequent update to either Hermes or OS X, I don't recall.
