### ISSUE TITLE
Edit Station: Added seeds do not show in list

### ISSUE THREAD

**Issue by DustBowlRefugee** [HermesApp/Hermes#252]
In the Edit Station window, after selecting a song or artist and clicking the "Add Seeds" button, the new seed does not show in the right hand list. If you exit the Edit Station window and go back in, the added seeds do show up.

**Comment by nriley** [comment]
I overhauled the seed editor stuff for 1.2.8. The seeds do show up for me now — can you test with the beta and let me know if it's fixed for you?

https://github.com/HermesApp/Hermes/releases/tag/v1.2.8b1

Thanks!

**Comment by deltamikeecho** [comment]
I can confirm that this works as expected for me in 1.2.8b3.
