### ISSUE TITLE
"internal pandora error" persistent

### ISSUE THREAD

**Issue by MACDBHAM** [HermesApp/Hermes#259]
After deleting a couple of stations last night It began to give me an error that said the following:
"internal pandora error" and would NOT move on or explain the error.
I know my account works as its on my android phone playing just fine.

**Comment by sheykh-sleky** [comment]
Getting same error, cannot connect to service?

**Comment by ryanbmilbourne** [comment]
I am also seeing this error.  See screenshot below:
![screen shot 2016-03-14 at 8 35 58 am](https://cloud.githubusercontent.com/assets/5648689/13749714/c994c9e2-e9bf-11e5-9335-00600ba3808b.png)
I don't seem to see any related errors in the system logs.

**Comment by Skinner927** [comment]
+1

**Comment by rtremmel** [comment]
+1

**Comment by omalley** [comment]
+1 for me too. Nothing changed, but now I can't connect at all.

**Comment by taferris** [comment]
I was also seeing this error.  I then signed into Pandora via a browser just to see if the site was up (it was).  When I went back to Hermes it worked fine...  strange...

**Comment by sheykh-sleky** [comment]
Well...  No shit.  I'm connected too.  Would have been nice to get more information on connectivity issues.  Ah well, back to headbanging.

**Comment by omalley** [comment]
Ok, that isn't working for me. I can log on to the website fine, but I am still getting the "Internal Pandora error".

**Comment by MACDBHAM** [comment]
Tried that tqice but no luck

**Comment by taferris** [comment]
Sorry, looks like the browser thing was a fluke.  I have now been hitting the issue occasionally.  Finally figured out how to get Hermes into debug mode (Hold down option key while launching: warning-finder will react to the option key as well)  It writes a log file for each launch into ~/Library/Logs/Hermes.

I find that if I have the app retry connecting, occasionally it will connect without issue.  When it doesn't connect, here is the message I am seeing:

```
Pandora.m:815 -[Pandora sendRequest:] https://tuner.pandora.com/services/json/?method=auth.userLogin&partner_id=42&auth_token=REDACTED&user_id=
HermesAppDelegate.m:328 -[HermesAppDelegate handlePandoraError:] error received {
    error = "The data couldn\U2019t be read because it isn\U2019t in the correct format.";
    request = "<PandoraRequest 0x7ffded8a3960 auth.userLogin>";
}

```
When it connects, the log looks like:
```
Pandora.m:815 -[Pandora sendRequest:] https://tuner.pandora.com/services/json/?method=auth.userLogin&partner_id=42&auth_token=REDACTED&user_id=
Pandora.m:263 __41-[Pandora doUserLogin:password:callback:]_block_invoke255 Subscriber detected, re-logging-in...
```

Makes me wonder if Pandora is making some API changes or if they have an auth server that is misbehaving and we are just getting load balanced to it...

**Comment by sheykh-sleky** [comment]
As it stands, there is no maintainer, right?  No one is actively working on Hermes anymore....?

**Comment by nriley** [comment]
That's correct. Please see #237. A few people have posted some patches, but someone needs to fork Hermes and start writing code, merging and testing if they want Hermes to continue. I really wish I had the ability to work on it any more, but I don't.

**Comment by ryanbmilbourne** [comment]
It's also worth noting that I was able to connect by deleting the pref plist for Hermes and logging out/in.

**Comment by MACDBHAM** [comment]
Oh? Was.updated within the past few months

**Comment by omalley** [comment]
Hmm, I tried deleting the cache, the plist and the password from the keychain. Still no luck.

**Comment by gilbreen** [comment]
Just adding that I am seeing the same behavior.  I thought I deleted the app and attached files and reinstalled, but got the same error.  However, as sheykh-sleky added to his comment, I repeatedly hit the 'Try Again' button and then it connected to Pandora, loaded my stations and started playing one of them.

Where are the pref files stored?  I use AppTrap and when I moved the app to the trash, it asked if I wanted to move the accompanying pref files to the trash and I selected 'yes'. But after I reinstalled, and was able to get it to play, I did not have to enter any Pandora info - it automatically pulled in my stations.

**Comment by giantspeck** [comment]
I don't think money is an issue; I think it's his time.

**Comment by nobecutan** [comment]
Had the same issue. For me it had to do with timeout (probably because of a slow proxy).
[patch.txt](https://github.com/HermesApp/Hermes/files/206437/patch.txt)

**Comment by omalley** [comment]
I have a fast connection (ping to www.pandora.com is avg 1.9 ms and max is
2.1 ms), but I get the error frequently. It turns out that for me, if I hit
"retry" enough times it eventually connects successfully.

.. Owen

**Comment by reedloden** [comment]
Looks like somebody already submitted a PR to fix this -- #256

**Comment by iyee** [comment]
@nriley Can you release a new binary since this PR had been merged, this bug is really confusing.

**Comment by nriley** [comment]
Will try to get to this in the next week — crazy busy next few days.

**Comment by nriley** [comment]
For anyone who is experiencing this problem, please try out https://sabi.net/temp/Hermes-1.2.7b1.zip and see if it works for you.  I'll release it if it works.  Also I'd like to consolidate discussion, so please see #244.

**Comment by rtremmel** [comment]
Thank you so much for fixing this error!!!
