### ISSUE TITLE
Domain Name Expired

### ISSUE THREAD

**Issue by fritz-fritz** [HermesApp/Hermes#261]
It appears that hermesapp.org has expired (except it technically hasn't).

<img width="1324" alt="screen shot 2016-04-08 at 9 57 15 am" src="https://cloud.githubusercontent.com/assets/5253894/14385820/5575b7d2-fd70-11e5-8dbd-8761afc654ed.png">

From a WHOIS lookup it seems the record was updated on 2016-04-04T10:59:02Z.

I understand @winny- has dropped the project and so may have let the domain expire. I assume this will also break the update mechanism?

Poking into the HermesApp Organization I see the website is hosted as a GitHub Page but attempting to reach the page with hermesapp.github.io redirects to hermesapp.org which has expired. This is probably due to the CNAME file in the repo (I haven't read up on how GitHub Pages work).

So maybe the fix is to renew the domain name or maybe it is to remove the CNAME and transition to the hermesapp.github.io URL.

(Not sure who is currently maintaining the project ala #237 so I'll go ahead and mention @nriley and @alexcrichton here too)

**Comment by nriley** [comment]
I have no idea about the domain registration but I emailed the other folks. If we can't rescue it I'll at least try to get hermesapp.github.io to work.

**Comment by nriley** [comment]
OK, turned out @winny- let the domain expire intentionally. This is now resolved. I think I'm now the only person who is responding to emails/issues. I'm happy to pay for domain fees but still have no time to spend on the project. I will try to put out some louder calls for help, including on the main Website as I get chance.
