### ISSUE TITLE
Station Edit | Likes/Dislikes or Seed list sort does not work

### ISSUE THREAD

**Issue by deltamikeecho** [HermesApp/Hermes#266]
Sorting either station Seed list or Likes/Dislikes list does not work.  Select "Song - Artist" sort button and nothing changes in the list.  List appears to be default sorted by descending date.

**Comment by nriley** [comment]
The Seeds list isn't sortable by design.  Likes/Dislikes was an oversight.  I implemented sorting but wonder if you'd prefer to have it sort by artist first?  Give this a shot:

https://sabi.net/temp/Hermes-1.2.8d3.zip

**Comment by nriley** [comment]
Closing this ticket since I haven't heard anything…

**Comment by deltamikeecho** [comment]
Now works as expected.  Thanks.
