### ISSUE TITLE
Hermes crashes on MacOS Sierra 10.12. 

### ISSUE THREAD

**Issue by q9alpha** [HermesApp/Hermes#268]
Its 
[HermesLog_2016-06-26_22:00:15_-0700.txt](https://github.com/HermesApp/Hermes/files/334143/HermesLog_2016-06-26_22.00.15_-0700.txt)
rather simple. It'll sometimes crash upon start-up, without a song playing for more than a minute. Audio becomes sort of choppy at times to signal that the application will crash. Other times, the application crashes after one skip, or upon a click to switch to a different station. This is seen with Hermes 1.2.8, with MacOS Sierra 10.12.

**Comment by q9alpha** [comment]
Apologies for the log file getting in the way of the description of the issue. I was not aware it would do that.

**Comment by nriley** [comment]
Thank you for attaching Hermes’ log. Everything looks good in there. I imagine that from the frequency and severity of the crashes that you were noticing that anyone who tries to test Hermes on 10.12 will have these problems. Unfortunately, I am unlikely to have a working 10.12 installation for the next few weeks as I need to install a new drive in one of my Macs.  If anyone else is running 10.12 and can do some debugging in the meantime, that would be great!

**Comment by nriley** [comment]
I have started fixing up Hermes to work on 10.12 and haven't been able to duplicate this.  Give this test version a shot:

https://sabi.net/temp/Hermes-1.2.9d1.zip

and let me know if it still is being flaky/crashing.  Thanks!

**Comment by nriley** [comment]
There's now a beta, with some more 10.12 specific changes:

https://github.com/HermesApp/Hermes/releases/tag/v1.2.9b1

**Comment by nriley** [comment]
1.2.9b2 is now out: https://github.com/HermesApp/Hermes/releases/tag/v1.2.9b2

If you are still interested, please test!  Thanks.

**Comment by q9alpha** [comment]
Seems as though Hermes works fine under MacOS Sierra 10.12. I am running the GM of it, and hermes 1.2.9 beta 2.

**Comment by nriley** [comment]
Awesome. Hope to have a final out in the next couple days.
