### ISSUE TITLE
Pause/play icons hard to see on Dock icon

### ISSUE THREAD

**Issue by chriscraig** [HermesApp/Hermes#277]
First, I just want to say I love this app and am very thankful to the maintainers.

With that out of the way I've noticed that the pause/play icons are hard to see on top of certain album art (e.g., lots of dark gray in the image) in the Dock when that preference is chosen.  I recommend that a high contrast outline be added to the icon.

**Comment by nriley** [comment]
Agreed. I'm really bad at graphics, anyone? :-)

**Comment by nriley** [comment]
Best I could do on short notice was a white shadow, but someone with some graphics skills could just make a nice graphic I could blend.

Is this better than nothing?

![shadow](https://cloud.githubusercontent.com/assets/68303/18824422/14cc6d1a-8390-11e6-9912-4bf3af611b37.png)

**Comment by paullj1** [comment]
Yeah, I kind of thought the same thing but I didn't want to add another image to the project. I can play with a few things, but it won't be for a few days. 

That said, I think the shadow @nriley tried looks good.

**Comment by paullj1** [comment]
I implemented that shadow and then made it much more distinct.  I think it looks pretty good.  Plus now you'll have the option of removing the play/pause entirely:

<img width="139" alt="screen shot 2016-09-28 at 19 59 46" src="https://cloud.githubusercontent.com/assets/8845575/18937485/33fbe698-85b6-11e6-8218-ecf468a987c2.png">

**Comment by nriley** [comment]
Looks good.  Might be a few days before I get to this as I'm having a very busy week!

**Comment by paullj1** [comment]
No worries, we've all been there!
