### ISSUE TITLE
Media Keys Quit Working on Sierra

### ISSUE THREAD

**Issue by xopey** [HermesApp/Hermes#281]
When I first launch Hermes, the media keys seem to work fine, but after some period of time, they quit responding. The only way I've found to recover is to quit and relaunch Hermes. I've made sure that iTunes isn't launching or running since I'm aware of the typical issues there.

**Comment by paullj1** [comment]
Any chance you're using the StreamKeys plugin for Google Chrome?  That stole focus for me, but went away when I closed Chrome.  Other than that, I haven't been able to re-create this problem.

**Comment by xopey** [comment]
Great suggestion paullj1, but unfortunately, that's not the source of my issue

**Comment by paullj1** [comment]
Hmm... well, I'll keep an eye out.  Still haven't been able to re-create.

**Comment by mattiowa** [comment]
I'm having the same problem on an iMac running Sierra 10.12.1.

**Comment by xopey** [comment]
I figured out that I had the Vox preferences installed. Although I uninstalled the Vox app, I forgot to uninstall the preferences app and found out it was stealing media keys. 

Corey Willis




On Thu, Oct 27, 2016 at 8:07 AM -0500, "mattiowa - notifications@github.com" <github.coreyw.ef53432dc9.notifications#github.com@ob.0sg.net> wrote:












I'm having the same problem on an iMac running Sierra 10.12.1.

**Comment by nriley** [comment]
Good news is that macOS 10.12.2 finally has non-hacky support for media keys so as part of the work I've done in #287 this stuff should start to work in the next version!  (It even works in debug builds!)

**Comment by nriley** [comment]
Does anyone actually use the feature whereby tapping the previous track button causes Hermes to come to the front? I had no idea this was even there…

**Comment by nriley** [comment]
Unfortunately 10.12.3 seems to have regressed here.  I'll test again in 10.12.4 when it comes out...
