### ISSUE TITLE
Cannot paste password w/keyboard

### ISSUE THREAD

**Issue by egomadking** [HermesApp/Hermes#286]
Cannot paste password w/keyboard. I can right-click paste though. I am using Mac OSX Sierra.

**Comment by nriley** [comment]
Command-V worked for me in the password field on Sierra (and I pasted my Pandora password a lot while testing the login process…).  Can you provide steps to reproduce this issue?  Thanks.

**Comment by egomadking** [comment]
I logged out, quit Hermes. Started it back up and CMD-V does not work- it gives me an OS X alert sound. I even quit LaunchBar (I use their pasteboard feature), re-copied my PW, then CMD-V with same result. Is there anything else that you want me to try?

I get the same result with the username field as well.

**Comment by nriley** [comment]
Tested some more and still couldn't reproduce.  Can you paste in other ways (from the Edit menu, if you have the menu bar visible, or by using the contextual menu)?  Are you able to paste into other text fields in Hermes after logging in?

**Comment by egomadking** [comment]
The only other fields that I found were in the network preferences. These too gave me the same result. I even ensured that I was copy/pasting an int.

Right-click works as well as well as menubar Edit->paste.

**Comment by nriley** [comment]
Do you see ⌘V in Hermes’ Edit menu next to Paste? Only thing I can think of at this point is that somehow this is getting intercepted or remapped…

**Comment by egomadking** [comment]
That's got it! I've got it mapped to "Paste and Match Style". Sorry...
