### ISSUE TITLE
New UI is uglier than it was in previous versions

### ISSUE THREAD

**Issue by JohnDDuncanIII** [HermesApp/Hermes#289]
It seems (in my totally subjective opinion) that the user interface looked better in older versions of Hermes. I'm not sure why, but the current version of Hermes does not seem to have a divider between the titlebar area and main app content below it. This, in my opinion, looked much better before. I'm not sure if this is a bug or a feature, but I can probably build custom versions on my own to fix this.
I was wondering if anyone else using the program agrees.

Here is a comparison between how it looked in older versions and how it looks now: 
![00b6c5d8-8afc-11e5-8905-ebb3e21a3958](https://cloud.githubusercontent.com/assets/9257785/21997473/91f8ee7e-dbfd-11e6-8322-e015f6a28301.png)

![screen shot 2017-01-16 at 3 05 21 pm](https://cloud.githubusercontent.com/assets/9257785/21997476/94659298-dbfd-11e6-9222-eb358acef621.png)

**Comment by nriley** [comment]
It's a feature.  I asked, and the small amount of feedback I got was supportive.  Feel free to make the change in your own version of course!

https://twitter.com/nriley/status/774216465415299073

**Comment by JohnDDuncanIII** [comment]
Gotcha. No worries. Will do!
