### ISSUE TITLE
Customized app icons don't show up in the dock

### ISSUE THREAD

**Issue by zachhowe** [HermesApp/Hermes#299]
I love Hermes, but the Hermes icon sticks out like a sore thumb on my dock. I'd like to customize the app icon by dragging and dropping a new icon file onto the Hermes icon shown in Finder's Get Info panel. Unfortunately Hermes sets it's dock icon on startup to either the album artwork or it's own "pandora" image. I have a fix which is as follows:

In HermesAppDelegate.m:573
`- (IBAction) updateDockIcon:(id)sender`

Instead of:
```
// change to the "pandora" icon
[NSApp setApplicationIconImage:[NSImage imageNamed:@"pandora"]];
```

Do this:
```
// reset the property
[NSApp setApplicationIconImage:nil];
```

When the property is reset, it defaults to the icon Finder will show, ie. the icon specified in the Info.plist or an icon the user specified.

If this is something you'd like to support, I can submit a pull request for this.

**Comment by nriley** [comment]
Sure, seems fine to use a custom icon in preference of the Hermes icon if you have it.  Do you have a better icon idea? :)

**Comment by zachhowe** [comment]
Personally I think the Hermes Icon looks too much like an iOS icon, square with the rounded corners. If a new icon were to be designed for Hermes, my preference would be a rounded icon like iTunes, iBooks, App Store, etc. That seems to be the design direction on macOS right now.

**Comment by nriley** [comment]
OK.  I barely have time to keep up with patches but if someone wants to make a new icon in that theme, I'm all for it...

Closing as your pull request is merged.
