### ISSUE TITLE
Latest update kills media keys

### ISSUE THREAD

**Issue by swampxiix** [HermesApp/Hermes#300]
Updated 3/27 when prompted by Hermes.

Update & relaunch. Now my media keys (play/pause on F8, etc.) don't work anymore. Now just launches iTunes whereas before it would control Hermes playback.

Restarted Mac to see if that fixed the problem; it did not.

This is Hermes 1.3.1 (2058) running on OS X 10.11.6 on a Mac Pro.

**Comment by swampxiix** [comment]
Went into preferences, "Control playback with media keys" was checked. I unchecked it, then rechecked it, and the media keys functionality is restored.

**Comment by nobecutan** [comment]
Thanks for the update. Worked for me as well.
