### ISSUE TITLE
Hermes now requires Xcode 8

### ISSUE THREAD

**Issue by ryandesign** [HermesApp/Hermes#307]
It is a shame that Hermes 1.3.1 requires Xcode 8 to be compiled. (1.3.0 could be compiled with Xcode 7.2 on Yosemite.) Hermes is the type of app that should be more conscious of compatibility with older systems than most, since it is a type of app that is especially well suited for use on older computers that have been relegated to a secondary life as media players, and it is those older computers that are more likely to be unable to be upgraded to new versions of the OS and consequently unable to upgrade to newer versions of Xcode.

On El Capitan with Xcode 7.3.1:

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_aqua_HermesApp/HermesApp/work/Hermes-1.3.1/Resources/English.lproj/MainMenu.xib: error: The document “(null)” requires Xcode 8.0 or later.
    Recovery Suggestion: This version does not support documents saved in the Xcode 8 format. Open this document with Xcode 8.0 or later.
```

On Snow Leopard with Xcode 3.2.6:

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_aqua_HermesApp/HermesApp/work/Hermes-1.3.1/Resources/English.lproj/MainMenu.xib: error: Interface Builder was unable to determine the type of "MainMenu.xib".
Interface Builder was unable to determine the type of "MainMenu.xib".
```

**Comment by nriley** [comment]
Agreed, and it's frustrating for me too as I still run 10.10 on one Mac — unfortunately in Xcode 8 any options for XIB compatibility prior to Xcode 7.x have been removed, and even *that* option doesn't work any more (it reverts immediately to Xcode 8.0).  Please file a Radar.
