### ISSUE TITLE
Sort liked songs by date

### ISSUE THREAD

**Issue by mondaiguy** [HermesApp/Hermes#310]
Would like to see the songs I've liked but sorted by date rather than ABC order. It's hard to figure out which songs I've liked recently in the current alphabetical list...

**Comment by nriley** [comment]
This is already supported.  If you keep clicking the “Artist - Song” column header, you toggle between alphabetical, reverse alphabetical and reverse chronological.  (At least that's the way things work for me!)

**Comment by mondaiguy** [comment]
Cool, guess you're right. Would be a nice touch if the "Artist - Song" column header changed to say "Newest to Oldest" or "Chronological" or something.

Thanks

**Comment by nriley** [comment]
Agree the UI is horribly overloaded.  Worth putting on the list :-)
