### ISSUE TITLE
Unable to retrieve the station selector

### ISSUE THREAD

**Issue by kylemhall** [HermesApp/Hermes#311]
I slid the station selector all the way to the left to it disappeared completely from view, and now I cannot find a way to get it back!
![hermes](https://user-images.githubusercontent.com/50537/27222936-591a9988-525c-11e7-81db-d5e605bc6cfd.png)

**Comment by kylemhall** [comment]
Figured out clicking the show song history button a second time switches to the station pullout.

**Comment by nriley** [comment]
Yup, you got it!  The toolbar drawer item will toggle between the two drawers.

If you are trying to figure out what's going on with the drawer, Hermes’ View menu is the best way to figure that out:

![hermes view menu](https://user-images.githubusercontent.com/68303/27252964-74e89b06-5338-11e7-8834-cc4f3813b9ec.png)

The “–” mark indicates that the drawer selected (history or stations) will become visible when you show the drawer.  A check mark indicates that particular drawer is visible.  You can use the keyboard equivalents even if you have Hermes’ menu bar hidden.

Drawers are finally officially deprecated in macOS High Sierra, so at some point we'll have to replace them with something else, perhaps an expanding window.
