### ISSUE TITLE
Show track history

### ISSUE THREAD

**Issue by jrittenh** [HermesApp/Hermes#312]
I often listen to a station and don't pay enough attention to what's playing to be able to vote a song up/down unless it's something really new to me and I like it or it doesn't fit the station at all.  Would it be possible to implement a track history of the current session similar to the seeds and likes/dislikes, or the station sidebar?

**Comment by nriley** [comment]
This already exists but is clearly not discoverable enough.  You can click the icon in the toolbar which will either be a broadcasting antenna (stations) or a clock with counterclockwise arrow (history), or use View → History or ⇧⌘H.

**Comment by jrittenh** [comment]
Ah thank you...and yeah, that wasn't exactly intuitive, but does precisely what I expected.  Thanks!

**Comment by nriley** [comment]
There should be a tooltip on that icon — you can also right-click the toolbar and choose "Icon & Text" to see labels on each of the buttons if you want.

<img width="490" alt="hover" src="https://user-images.githubusercontent.com/68303/27596853-c3f69fc4-5b2e-11e7-9770-5a58d0f14a05.png">

**Comment by jrittenh** [comment]
I swear that tooltip wasn't there before...tried and tried to make it appear, no luck.  You send a comment, I go back and try again, voilà!  Witchcraft.  I'll go with that.
