### ISSUE TITLE
Is it necessary to log in ever time Hermes is opened?

### ISSUE THREAD

**Issue by rpitcairn** [HermesApp/Hermes#319]
I downloaded it tonight, looks very nice but every time I open it have to log in Pandora each time. Is this acting normal? Most software not like this. Maybe there is something I am supposed to set up?

— Richard

**Comment by rpitcairn** [comment]
Never mind. Figured it out. Was something not right with my computer.

**Comment by nriley** [comment]
Glad you got it figured out. Hermes stores this information in the keychain and I would suspect that there may have been something wrong with your keychain set up if this was failing.
