### ISSUE TITLE
Hermes crashes on 10.13.1 when loading the playlist

### ISSUE THREAD

**Issue by adamrabbit** [HermesApp/Hermes#321]
I have a fresh install of 10.13.1. It's set up exactly the same as the previous install with 10.12, but now Hermes crashes when the playlist loads. I've tried deleting all the files and keychain entries and reinstalling but the problem persists. I'm not sure what else it could be since it's a completely fresh install...

edit: ugh. no audio. It's not launching because the audio device isn't registering in the system. sorry for this needless post!

**Comment by nriley** [comment]
Sorry, no problem — it looked like Apple's bug (and I've had magical disappearing audio devices on 10.13 too.)
