### ISSUE TITLE
Feature Request: Thumbprint Radio

### ISSUE THREAD

**Issue by Raab70** [HermesApp/Hermes#326]
Is there any way we can implement thumbprint radio? I don't see it exposed through the API. (https://6xq.net/pandora-apidoc/json/methods/). As far as I can tell it's a song seeded by every song you've ever liked on any station (http://blog.pandora.com/us/thumbprint-radio-a-uniquely-personal-station-inspired-by-all-of-your-thumbs-up/). 

We could possibly create our own for songs liked through the app which updates automatically as new songs are liked. Although I'm not sure how to get all the other songs a user has liked on other platforms.

**Comment by nriley** [comment]
Thumbprint Radio shows up in my copy of Hermes as a station — perhaps because I interacted with it on the Web or iOS.  Does it not for you?

**Comment by Raab70** [comment]
Interacting and then a station refresh got it to appear.
