### ISSUE TITLE
Work with BeardedSpice

### ISSUE THREAD

**Issue by pstew** [HermesApp/Hermes#334]
Please consider adding support with BeardedSpice https://beardedspice.github.io/ . It's currently the only way I can get my media keys to work with media players. Thank you!

**Comment by nriley** [comment]
From what I can tell the appropriate place to file an issue is in
BeardedSpice not in Hermes.  The appropriate scripting support should
already be in place as I've built something similar myself
(https://github.com/nriley/StreamVision/blob/master/StreamVision.py,
though I would not recommend you use it!)

On Mon, May 21, 2018 at 07:41:55AM -0700, Paul Stewart wrote:
> Please consider adding support with BeardedSpice https://beardedspice.github.io/ . It's currently the only way I can get my media keys to work with media players. Thank you!
> 

--Nicholas
