### ISSUE TITLE
"An error has occured with Pandora"

### ISSUE THREAD

**Issue by takmad** [HermesApp/Hermes#339]
I'm getting an error with Hermes 1.3.1.  New for today.  See attached screen capture.

I tried restarting and a few things, but no luck.  I'm a big fan of Hermes so hopefully this will resolve.

![hermes](https://user-images.githubusercontent.com/957409/43736887-4b140c60-998d-11e8-84f6-ff2b60d1106a.jpeg)

**Comment by ciphershort** [comment]
+1    Having the same issue today as well.

**Comment by jrearick** [comment]
Here is what I'm getting in the logs when it fails. SSL issue?

`default	15:04:28.185704 -0500	Hermes	TCP Conn [6:0x604000168280] using empty proxy configuration
default	15:04:28.185726 -0500	Hermes	Stream client bypassing proxies on TCP Conn [6:0x604000168280]
default	15:04:28.185743 -0500	Hermes	TCP Conn 0x604000168280 started
default	15:04:28.185873 -0500	Hermes	[6 <private> <private>] start
default	15:04:28.236033 -0500	Hermes	TCP Conn 0x604000168280 event 1. err: 0
default	15:04:28.236228 -0500	Hermes	TCP Conn 0x604000168280 complete. fd: 12, err: 0
default	15:04:28.236419 -0500	Hermes	TCP Conn 0x604000168280 starting SSL negotiation
default	15:04:28.291295 -0500	Hermes	Trust evaluate failure: [leaf GrayListedKey]
default	15:04:28.291335 -0500	Hermes	CFNetwork SSLHandshake failed (-9807)
error	15:04:28.291383 -0500	Hermes	TCP Conn 0x604000168280 SSLHandshake failed (-9807)
default	15:04:28.291609 -0500	Hermes	TCP Conn 0x604000168280 canceled
default	15:04:28.291717 -0500	Hermes	[6 <private> stream, pid: 13025] cancelled
	[6.1 2F5F92DA-3DD0-4357-9BF0-4A83D29E659D <private>.53637<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns
	Duration: 0.105s, DNS @0.000s took 0.001s, TCP @0.002s took 0.048s
	bytes in/out: 3007/151, packets in/out: 3/1, rtt: 0.046s, retransmitted packets: 0, out-of-order packets: 0
`

**Comment by vahramdodoryan** [comment]
+1

**Comment by kshafer1** [comment]
Workaround is posted here:
https://github.com/HermesApp/Hermes/issues/337

need to trust an old certificate

**Comment by nriley** [comment]
Closing this as a duplicate.
