### ISSUE TITLE
An error has occurred with Pandora.  [Try Again] - Internal Pandora error

### ISSUE THREAD

**Issue by cybiant** [HermesApp/Hermes#340]
I've not used the app since last Friday and starting today when I try to launch it I get the error message above.   I've tried reinstalling, but that doesn't correct the issue.

**Comment by jbone1210** [comment]
I have the same issue and have tried reinstalling as well.

Did Pandora shut it down?

**Comment by jeffpasch** [comment]
same here.

**Comment by charleshimmer** [comment]
Used it everyday and then on Wednesday it just stopped working.  It feels like maybe Pandora somehow blocked it.

**Comment by RocketGS** [comment]
Just downloaded this app and I'm getting this same issue. Bummer!

**Comment by inieves** [comment]
Im getting the same issue.

i have contacts over at Pandora... should I contact them?

Log attached:
==========================
HermesAppDelegate.m:195 -[HermesAppDelegate applicationDidFinishLaunching:] Starting in debug mode. Log file: /Users/inieves/Library/Logs/Hermes/HermesLog_2018-08-10_12:49:11_-0400.log
Pandora.m:290 -[Pandora doPartnerLogin:] Getting partner ID...
Pandora.m:823 -[Pandora sendRequest:] https://tuner.pandora.com/services/json/?method=auth.partnerLogin&partner_id=&auth_token=&user_id=
Pandora.m:823 -[Pandora sendRequest:] https://tuner.pandora.com/services/json/?method=auth.userLogin&partner_id=42&auth_token=VADEjNzUq9Ew9%2BIlY%2BmhA%2BN08yGZjtcuma&user_id=
Pandora.m:270 -[Pandora doUserLogin:password:callback:]_block_invoke Subscriber status: 1
Pandora.m:275 -[Pandora doUserLogin:password:callback:]_block_invoke Subscriber detected, re-logging-in...
Pandora.m:290 -[Pandora doPartnerLogin:] Getting partner ID...
Pandora.m:823 -[Pandora sendRequest:] https://internal-tuner.pandora.com/services/json/?method=auth.partnerLogin&partner_id=&auth_token=&user_id=
HermesAppDelegate.m:713 -[HermesAppDelegate handlePandoraError:] error received {
    error = "The operation couldn\U2019t be completed. (OSStatus error -9807.)";
    request = "<PandoraRequest 0x60400029e410 auth.partnerLogin>";
}

**Comment by RGerboth** [comment]
Looks like maybe Pandora locked Hermes out. Same issue on brand-new install.

**Comment by ryanbeymer** [comment]
I was poking around.... looks like their wildcard cert is busted.

- go to https://tuner.pandora.com/ - invalid cert 
- go to https://internal-tuner.pandora.com/ - invalid cert

**Comment by nobecutan** [comment]
There was a thread the other day regarding this issue. Basically Apple and Chrome and others effectively killed a bunch of CAs owned by Symantec. 

As a workaround you have to manually trust the specific TLS certificate and all is gay again.  

BR Christof

**Comment by nobecutan** [comment]
The related issue plus a step by step instruction is #337.

**Comment by inieves** [comment]
Also worked for me, thanks!  Does this need to become part of usage instructions or some FAQ? Or a popup? Thanks @nobecutan #337 (comment)

**Comment by charleshimmer** [comment]
Worked for me! Thanks!

**Comment by ZevEisenberg** [comment]
How wise is it to manually trust certs that have been marked as untrusted by Apple and Google? Can we trust them only for pandora.com URLs?

**Comment by DanielStormApps** [comment]
Created a PR if anyone would like to help test #341

**Comment by HashRocketSyntax** [comment]
sounds like a change in the auth pattern

**Comment by nriley** [comment]
I can just turn things off completely (30497ade27adc0894e2034eb572904866d63148e) which does work, but want to do a better job. SecureTransport has defeated me today with its inscrutable documentation, but if anyone can help with pinning the cert or CA, that'd be awesome.

**Comment by foliovision** [comment]
In the meantime, what makes Hermes work with no fussing around with certificates is to **open the normal Pandora app (2.0.10 on my computer) and pause it**. If you have Hermes open it will start to work once Pandora's native app starts working once. You must leave the Pandora app open and paused though.

I prefer Hermes [not only for the efficient interface](https://foliovision.com/2017/02/hermes-pandora-client) but for the LastFM scrobbling. Last.FM has been kind of a favourites list of last resort for awhile when listening across Deezer, Tidal, Pandora, Soma FM and any other service I try. Thanks to Soundiiz (annual subscription for full feature set, free one off migrations), it's possible to convert and amalgamate favourite track, artist and album listings across services with relatively minimal hassle (you have to be a bit of a geek to get along with Soundiiz still).

This works even when running Pandora over a [site specific VPN for Hermes](https://foliovision.com/2015/11/site-specific-vpn-pandora). My guide for the site specific VPN, still works, I had to re-use the guide myself today as I've been listening to a lot of SomaFM (West Coast 70's and Lush are awesome free channels, donated there too though). With Clementine app (GPL) you get an easy to use and fast to start interface for digital channels (outside the browser), along with Last.fm scrobbling. I mention Clementine as many of those who admire Hermes like I do might light Clementine too.

**Comment by sandinak** [comment]
imported the cert as noted in #337 and still getting internal error.

**Comment by nriley** [comment]
Might be the intermediate cert.

https://github.com/HermesApp/Hermes/issues/340

As I mentioned in #340 the only Hermes-side for this (aside from
Pandora fixing things) is to rewrite Hermes' non-streaming networking
such that we can intercept and override certificate validation.  I'm
working on it slowly and will get my WIP onto a branch this weekend,
but I can't devote more than 2-3 hours a week to it given other
responsibilities, and I suspect it'll be more like 6-10 hours of work
to do because I've never used NSURLSession before.

On Wed, Sep 05, 2018 at 02:17:36PM +0000, Branson Matheson wrote:
> imported the cert as noted in #337 and still getting internal error. 
> 

-- 
--Nicholas

**Comment by inieves** [comment]
If you have any tough questions let me know.  I can forward to colleagues who are former apple engineers.  They would be able to answer questions in that domain.

-ian

**Comment by haozhang96** [comment]
> imported the cert as noted in #337 and still getting internal error. After doing some digging I found it's failing because the intermediate is also marked as not trusted. I imported the cert and intermediate from internal-tuner.pandora.com, I marked it as trusted temporarily and that resolved the issue; however not happy with having to do that. I know it's pandora's issue .. but meh .. it's dirty.

This did it for me. Thanks!

**Comment by tomlogic** [comment]
I was able to do it by importing and trusting just the cert from https://internal-tuner.pandora.com/ which I had not realized was a different cert from https://tuner.pandora.com/ (which I had previously imported).  They're both wildcard certs, but with different expiration times.

**Comment by andrewrphillips** [comment]
@tomlogic This did it for me!

**Comment by nriley** [comment]
Merging this with #337 as it's the same issue.
