### ISSUE TITLE
v1.3.1 stopped working on 2018-09-13

### ISSUE THREAD

**Issue by tomlogic** [HermesApp/Hermes#343]
Been happily using Hermes for years, but it stopped working yesterday.  Wondering if recent commits to master resolve the issue (SSL certificates?) and if there are plans for an "official" release in the near future.  I tried building myself, but the build failed since I don't have a signing certificate:
```
xcodebuild -project Hermes.xcodeproj SYMROOT=build -configuration Debug -scheme Hermes 
Build settings from command line:
    SYMROOT = build

=== BUILD TARGET Hermes OF PROJECT Hermes WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Error: No signing certificate "Developer ID Application" found:  No "Developer ID Application" signing certificate matching team ID "CYEL96ZVC2" with a private key was found.

** BUILD FAILED **
```

I tried building the `travis` target, but that fails with:
```
The following build commands failed:
	CompileXIB Resources/English.lproj/MainMenu.xib
(1 failure)
```

I'm an embedded ARM developer, so I'm not familiar with the macOS toolchain.

**Comment by tomlogic** [comment]
Sorry, seeing this is a duplicate of #340.  Closing.

**Comment by disconn3ct** [comment]
I know this is abandoned but this issue isn't a duplicate. This is about getting started with Xcode so that it can be built in Apple's walled-garden.

If anyone has a walkthrough on switching certs that would be great, seems like a few of us are trying to work out issues..
