### ISSUE TITLE
Immediately fails with "An error has occurred with Pandora".

### ISSUE THREAD

**Issue by wduquette** [HermesApp/Hermes#345]
Since Monday, 9/24/2018, after I upgraded my Mac to High Sierra, the Hermes window displays the following immediately on startup:

"An error has occurred with Pandora.  [Try Again]  (!) Internal Pandora error".

I've seen this error in the past, usually after Hermes has been playing for a while, and it usually goes away if I restart the app, switch to a different station, or press "Try Again".  In this case, I can't do anything.  The Pandora menu is completely disabled,  and "Try Again" does nothing.  I've tried every day this week, and each time it shows the error immediately on startup.

**Comment by nriley** [comment]
Are you a Pandora Plus (One) member? If so this is as a result of Pandora not replacing their certificate for internal-tuner.pandora.com.

Please see https://github.com/HermesApp/Hermes/issues/337#issuecomment-410788166 for instructions on how to trust this certificate (except replace tuner.pandora.com with internal-tuner.pandora.com).

**Comment by wduquette** [comment]
That's lovely: exactly the problem, and the solution works perfectly.  Thanks very much!
