### ISSUE TITLE
Play/Pause keyboard shortcut does not work on MacOs Mojave

### ISSUE THREAD

**Issue by ahmed-musallam** [HermesApp/Hermes#349]
First of all, awesome app and works great!

### Device/OS:
 - MacBook Pro (Retina, 15-inch, Mid 2014)
 - MacOs Mojave 10.14.2

### Issue
The keyboard <kbd>fn</kbd> shortcut for fast-forward  <kbd>▶▶</kbd> works! it moves to the next song! (this is the same keyboard key for <kbd>f9</kbd> on my keyboard)
**However**, The play/pause <kbd>▶❙❙ </kbd> shortcut **does not** resume/stop the current song. Is there any reason for this, or a work-arround ?  (this is the same keyboard key for <kbd>f8</kbd> on my keyboard)

**Comment by nriley** [comment]
Unfortunately, as far as I know, this is just doomed to be flaky until Apple ever gives us an “official” way to support the play/pause key.

I suspect you may have another app open, or did at the time you started Hermes, which also wants to respond to the play/pause key. ITunes is a common culprit. I would recommend that you try to quit iTunes or other media applications before starting Hermes.

**Comment by ahmed-musallam** [comment]
@nriley I see, thank you, I'll close this then and try to find a solution.
