### ISSUE TITLE
Won't run on Mojave

### ISSUE THREAD

**Issue by dtolhurst** [HermesApp/Hermes#351]
I recently upgraded my computer to Mojave, and now I can't get the app to run at all.  I double click on the icon, and it looks like it's opening, but then nothing happens.  I tried deleting and reinstalling, but same thing.  On latest v. 1.3.1.

**Comment by nriley** [comment]
Works for me. No crash? Try logging out and back in.

**Comment by dtolhurst** [comment]
Log out of what?  I was already logged out of Pandora (on the site), but I just tried logging back in there with no effect (on Hermes).  I can't log out in Hermes because the app won't even open.

**Comment by nriley** [comment]
Out of your user account (Apple menu > Log Out).

**Comment by dtolhurst** [comment]
Didn't help.

**Comment by nriley** [comment]
Try a different user account?

**Comment by dtolhurst** [comment]
This is a work computer, so I don't have that ability.

**Comment by nriley** [comment]
Hmm, wonder if there’s some kind of antivirus or firewall software that is blocking Hermes then?

**Comment by dtolhurst** [comment]
I didn't think about it since it was working before, but I think we are upgrading to Mojave for security purposes, so that could be the case.  In any case, if it's working for others on Mojave, it seems like it's something more specific to my setup, so I'll close this issue.

**Comment by JohnLockeNJ** [comment]
I just upgraded from El Capitan to Mojave and Hermes stopped working.  Same as OP, I click on the app to open it and nothing happens.

**Comment by JohnLockeNJ** [comment]
I figured it out.  In Mojave and later you have to go into Preferences, Security & Privacy, and Accessibility, then click the lock to make changes and check the box to give Hermes permission.  Then it worked as before.

**Comment by nriley** [comment]
Glad you figured it out! Hermes should be updated to detect this situation at some point.
