### ISSUE TITLE
No longer functions under Catalina

### ISSUE THREAD

**Issue by khudson** [HermesApp/Hermes#361]
The app won't launch under Catalina and bails out with an abort. I tried building this myself under the newest Xcode to try and get around the problem but it persists. 

```nemesis% ./Hermes
Assertion failed: (_eventPort != NULL), function -[SPMediaKeyTap startWatchingMediaKeys], file /Users/(removed)/git/Hermes/ImportedSources/SPMediaKeyTap/SPMediaKeyTap.m, line 76.
zsh: abort      ./Hermes```

**Comment by nriley** [comment]
Please see #342. I wish I had time to work on this right now but I don't.
