### ISSUE TITLE
Popping audio on M1 MacBook Pro (macOS Monterey 12.2.1)

### ISSUE THREAD

**Issue by tomlogic** [HermesApp/Hermes#370]
A recent issue I've been having is popping/glitching audio when playing music in Hermes.  I'm not sure if it's tied specifically to Hermes or not.

If I play audio from pandora.com in my browser, I don't get any popping.

This may have started with 12.2.1 -- I don't recall it happening when I first got the computer a few months ago.

I'll update this issue if the problem goes away after updating to 12.3.

**Comment by tomlogic** [comment]
Closing this out as it is affects other audio apps, including Apple's own Music app.  And a Google search turns up many people affected by the issue.

**Comment by bkaid** [comment]
I have this same issue with Hermes on an M1 MacBook as well.  Spotify on the same laptop doesn't have the issue.

**Comment by dtseto** [comment]
> I have this same issue with Hermes on an M1 MacBook as well. Spotify on the same laptop doesn't have the issue.

https://github.com/dtseto/Hermes-master Please test my native apple silicon port of hermes. I have an apple signed notarized patched version for arm and a patched version for intel. Both work ok on my m1 mac running 15.5 and intel mac pro running 11.0+ but I need testers to identify issues. Thank you.
