### ISSUE TITLE
kCFErrorDomainCFNetwork error 2

### ISSUE THREAD

**Issue by klinden** [HermesApp/Hermes#375]
<img width="238" alt="image" src="https://github.com/HermesApp/Hermes/assets/2184972/81a8ad0a-47cb-49fa-b6bb-8b5aed45d3ec">

I just started noticing this yesterday. Seems like maybe it is a DNS issue according to some basic Googling I did. Curious if others are seeing this as well.

**Comment by klinden** [comment]
Signing out and back in again fixed the issue.

**Comment by nriley** [comment]
Yeah, we could do better with some of these error messages. Glad you got it figured out.
