### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by marckrejci** [HermesApp/Hermes#95]
Love the app, great implementation!  However, the app icon leaves much to be desired. When switching apps, I always feel like I'm going to a WebMD app.  Any plans on making it more music/Pandora related?  Want some help (ie If I create one for you, would you add it)? Maybe something like this: http://cl.ly/image/0W1h3L1a330s

**Comment by dwaite** [comment]
oh fun, I was also playing around with ideas in the same vein. 

http://cl.ly/2K0P3l0n2g3G
